export {default as HomeScreen} from './home'
export {default as SelectTasks} from './select-tasks'
export {default as Scores} from './scores'
export {default as LoginScreen} from './login'
export {default as PlayerDetail} from './player-detail'
export {default as PlayerDetailEdit} from './player-detail-edit'
